
<?php
/**
 * The following file has been generated by CodeGenPHP. 
 * Make sure you don't edit any of the files, because they will be overwritten by the next run. 
 * 
 * Made by CodeGenPHP - author: Steven K https://stevenkoerts.nl/
*/


        require_once('../../../config.php');
        require_once('../../../utils/DefaultHeaders.php');
        require_once('../../../utils/DbConnection.php');
        require_once('../../../utils/HttpResult.php');
        require_once('../../../utils/utils.php');
        
        if (!allow_request_methods(["PUT"])) {
            die("Request not allowed");
        }
        
        $data = json_decode(file_get_contents("php://input")); 
        $connection = new DbConnection();
    
        
    if ( isset($data->locationId) and isset($data->theater_showId)) {
        $result = $connection->ExecuteQuery("UPDATE location_theater_show SET locationId = $data->locationId, theater_showId = $data->theater_showId WHERE theater_showId = $data->theater_showId");
        
        if ($result === TRUE) {
            echo json_encode(new HttpResult($result, 200));
        } else {
            echo json_encode(new HttpResult($result, 500));
        }
    } else {
        echo json_encode(new HttpResult('Not all fields are filled in correctly', 402));
    }
    
    
        

?>