
<?php
/**
 * The following file has been generated by CodeGenPHP. 
 * Make sure you don't edit any of the files, because they will be overwritten by the next run. 
 * 
 * Made by CodeGenPHP - author: Steven K https://stevenkoerts.nl/
*/


        // TODO: UpdateMany snippet 

        echo json_encode(new HttpResult("Not implemented yet", 200));
        

?>